application: cloudalways
version: 1
runtime: python
api_version: 1

handlers:
- url: /test.*
  script: gaeunit.py
- url: /shape.*
  script: handlers/shape.py
- url: /data.*
  script: handlers/data.py
